name: MemoryCitadel CI

workflows:
  version: 1
  build-test:
    name: Build and Test
    trigger:
      event: pull_request
    jobs:
      - run-tests

jobs:
  run-tests:
    name: Unit and UI Tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build and test
        run: |
          xcodebuild \
            -scheme MemoryCitadel \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -enableCodeCoverage YES \
            test
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: unit
          fail_ci_if_error: true
          files: \
            ${{ github.workspace }}/build/reports/coverage/*.json